### ISSUE TITLE
有验证码哎。。。

### ISSUE THREAD

**Issue by Nipi64310** [Joy818/cet_query#1]
扎心了

**Comment by skyjerry** [comment]
same problem.. Please test @Joy818

**Comment by mkit777** [comment]
学信网，查询次数少的情况下没有验证码。大约一个IP50次左右吧，多了就会有验证码。
还有一个姓名查询太多次也会有验证码。
这个版本是有些问题，我是为了方便在另一个主机上测试才上传的。
我稍后会完善一下。

**Comment by mkit777** [comment]
刚刚试了一下，没有问题了。

**Comment by ly20180228** [comment]
请问为什么输入什么都会直接显示成功，而这个结果又是完全错误的呢？
