### ISSUE TITLE
请问验证码问题怎么解决

### ISSUE THREAD

**Issue by PreJuDiceC** [Joy818/cet_query#2]
我尝试的次数太多了，我现在用我同学的正确信息去尝试也是失败，应该是卡在验证码那了，请问要怎么解决呢

**Comment by mkit777** [comment]
很抱歉，失败的原因可能写入文件错误造成的
我已经修复，在我电脑上测试已没有问题，请重新尝试
如果真的出现验证码只能换个IP尝试了

**Comment by PreJuDiceC** [comment]
好的，谢谢回复，我待会儿自己尝试，
